import React, { useEffect, useRef, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, BookOpen, Edit3, FileText, Plus, Save, Trash2, Upload } from 'lucide-react';
import { createLesson, deleteLesson, getLessonsByModule, getModulesByCourse, type Lesson, type Module, updateLesson } from '@/api/module';
import { getCourses } from '@/api/course';
import { uploadFile } from '@/api/upload';
import AdminManageQuizModal from '@/components/module/AdminManageQuizModal';

const AdminModuleLessonsPage: React.FC = () => {
    const { courseId, moduleId } = useParams<{ courseId: string; moduleId: string }>();
    const navigate = useNavigate(); const fileRef = useRef<HTMLInputElement>(null);
    const [module, setModule] = useState<Module | null>(null); const [lessons, setLessons] = useState<Lesson[]>([]); const [courseImage, setCourseImage] = useState('');
    const [showAdd, setShowAdd] = useState(false); const [title, setTitle] = useState(''); const [content, setContent] = useState(''); const [video, setVideo] = useState(''); const [saving, setSaving] = useState(false); const [quizOpen, setQuizOpen] = useState(false);
    const load = async () => { if (!courseId || !moduleId) return; const [modules, lessonData, courses] = await Promise.all([getModulesByCourse(courseId), getLessonsByModule(moduleId), getCourses()]); setModule(modules.find(item => item.id === moduleId) ?? null); setLessons(lessonData); setCourseImage(courses.find(item => item.id === courseId)?.thumbnail ?? ''); };
    useEffect(() => { load().catch(console.error); }, [courseId, moduleId]);
    const upload = async (file?: File) => { if (!file) return; const result = await uploadFile(file); setVideo(result.url); };
    const add = async (event: React.FormEvent) => { event.preventDefault(); if (!moduleId || !title.trim() || !content.trim()) return; setSaving(true); try { await createLesson(moduleId, { title, content, video: video || undefined }); setTitle(''); setContent(''); setVideo(''); setShowAdd(false); await load(); } finally { setSaving(false); } };
    const style = courseImage ? { backgroundImage: `linear-gradient(rgba(9,16,24,.82),rgba(9,16,24,.92)), url(${courseImage})`, backgroundSize: 'cover', backgroundPosition: 'center' } : undefined;
    return <div className="max-w-5xl mx-auto space-y-7 pb-16"><button onClick={() => navigate(`/admin/courses/${courseId}/modules`)} className="flex items-center gap-2 text-sm font-semibold text-gray-500 hover:text-black"><ArrowLeft className="w-4 h-4" /> Back to Modules</button><header style={style} className="rounded-3xl bg-gray-950 text-white p-8"><p className="text-[#d0a868] text-xs font-black uppercase tracking-[.2em]">Module curriculum</p><h1 className="text-3xl font-black mt-2">{module?.title ?? 'Module lessons'}</h1><p className="text-white/65 mt-3">Create and order the lessons learners must complete before the module quiz.</p></header><div className="flex flex-wrap gap-3"><button onClick={() => setShowAdd(value => !value)} className="bg-gray-950 text-white rounded-xl px-5 py-3 text-sm font-bold flex items-center gap-2"><Plus className="w-4 h-4" /> Add Lesson</button><button onClick={() => setQuizOpen(true)} className="border border-[#d0a868]/40 bg-[#d0a868]/10 text-[#8d682f] rounded-xl px-5 py-3 text-sm font-bold flex items-center gap-2"><FileText className="w-4 h-4" /> Manage Module Quiz</button></div>{showAdd && <form onSubmit={add} className="bg-white rounded-3xl border border-gray-100 p-6 space-y-4 shadow-sm"><h2 className="font-black">New Lesson</h2><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Lesson title" className="w-full border rounded-xl px-4 py-3"/><textarea value={content} onChange={e => setContent(e.target.value)} placeholder="Lesson description" rows={4} className="w-full border rounded-xl px-4 py-3"/><input ref={fileRef} type="file" accept="video/*" className="hidden" onChange={e => upload(e.target.files?.[0]).catch(console.error)}/><button type="button" onClick={() => fileRef.current?.click()} className="w-full rounded-xl border-2 border-dashed border-gray-200 py-5 text-sm font-bold text-gray-500 flex items-center justify-center gap-2"><Upload className="w-4 h-4" /> {video ? 'Video uploaded — choose another' : 'Upload lesson video'}</button><button disabled={saving || !title || !content} className="bg-gray-950 text-white rounded-xl px-5 py-3 text-sm font-bold">{saving ? 'Saving…' : 'Create Lesson'}</button></form>}<section className="space-y-3"><div className="flex justify-between"><h2 className="font-black">Lessons</h2><span className="text-xs font-bold text-gray-400">{lessons.length} lessons</span></div>{lessons.map((lesson,index)=><LessonCard key={lesson.id} lesson={lesson} index={index} image={courseImage} moduleId={moduleId!} reload={load}/>) }{!lessons.length && <div className="rounded-3xl border border-dashed border-gray-200 py-14 text-center"><BookOpen className="w-9 h-9 text-gray-200 mx-auto mb-3"/><p className="font-bold">No lessons yet</p></div>}</section><AdminManageQuizModal moduleItem={module} isOpen={quizOpen} onClose={() => setQuizOpen(false)}/></div>;
};

const LessonCard: React.FC<{lesson: Lesson; index:number; image:string; moduleId:string; reload:()=>Promise<void>}> = ({lesson,index,image,moduleId,reload}) => { const [edit,setEdit]=useState(false); const [title,setTitle]=useState(lesson.title); const [content,setContent]=useState(lesson.content); const file=useRef<HTMLInputElement>(null); const upload=async(f?:File)=>{if(!f)return;const r=await uploadFile(f);await updateLesson(moduleId,lesson.id,{video:r.url});await reload();}; const save=async()=>{await updateLesson(moduleId,lesson.id,{title,content});setEdit(false);await reload();}; const remove=async()=>{if(confirm(`Delete “${lesson.title}”?`)){await deleteLesson(moduleId,lesson.id);await reload();}}; return <article style={image?{backgroundImage:`linear-gradient(rgba(255,255,255,.92),rgba(255,255,255,.98)),url(${image})`,backgroundSize:'cover'}:undefined} className="rounded-2xl border border-gray-100 p-5 shadow-sm"><div className="flex gap-3"><span className="w-8 h-8 shrink-0 bg-gray-950 text-white rounded-full grid place-items-center text-xs font-black">{index+1}</span><div className="flex-1 min-w-0">{edit?<><input value={title} onChange={e=>setTitle(e.target.value)} className="w-full border rounded-lg px-3 py-2 font-bold"/><textarea value={content} onChange={e=>setContent(e.target.value)} rows={3} className="w-full border rounded-lg px-3 py-2 mt-2 text-sm"/><button onClick={save} className="mt-3 text-sm font-bold text-[#8d682f] flex gap-2 items-center"><Save className="w-4 h-4"/>Save changes</button></>:<><h3 className="font-bold text-gray-900">{lesson.title}</h3><p className="text-sm text-gray-600 mt-1">{lesson.content}</p>{lesson.video?<video src={lesson.video} controls muted className="w-full max-w-md rounded-xl bg-black mt-4"/>:<><input ref={file} type="file" accept="video/*" className="hidden" onChange={e=>upload(e.target.files?.[0]).catch(console.error)}/><button onClick={()=>file.current?.click()} className="mt-4 text-sm font-bold text-[#8d682f] flex items-center gap-2"><Upload className="w-4 h-4"/>Upload lesson video</button></>}</>} </div><div className="flex gap-2"><button onClick={()=>setEdit(!edit)} className="p-2 text-gray-500"><Edit3 className="w-4 h-4"/></button><button onClick={remove} className="p-2 text-red-400"><Trash2 className="w-4 h-4"/></button></div></div></article>; };
export default AdminModuleLessonsPage;
